### ISSUE TITLE
verify-settings unexpected crash with incorrect API url

### ISSUE THREAD

**Issue by slarse** [slarse/repomate#101]
If one uses the host url for a GitHub instance, this happens:

```
$ repomate verify-settings -g https://gits-15.sys.kth.se
[INFO] config file defaults:

   user: slarse
   github_base_url: https://gits-15.sys.kth.se/api/v3
   org_name: inda-17
   
[INFO] verifying settings ...
[INFO] trying to fetch user information ...
[INFO] SUCCESS: found user slarse, user exists and base url looks okay
[INFO] verifying oauth scopes ...
[ERROR] TypeError: 'NoneType' object is not iterable
(repomate-EQUnzodV) [repomate 2011] $ repomate verify-settings -g https://gits-15.sys.kth.se -tb
[INFO] config file defaults:

   user: slarse
   github_base_url: https://gits-15.sys.kth.se/api/v3
   org_name: inda-17
   
[INFO] verifying settings ...
[INFO] trying to fetch user information ...
[INFO] SUCCESS: found user slarse, user exists and base url looks okay
[INFO] verifying oauth scopes ...
[ERROR] critical exception
Traceback (most recent call last):
  File "/home/slarse/Documents/github/cdate/repomate/repomate/main.py", line 55, in main
    cli.dispatch_command(parsed_args, api)
  File "/home/slarse/Documents/github/cdate/repomate/repomate/cli.py", line 180, in dispatch_command
    args.user, args.org_name, args.github_base_url, git.OAUTH_TOKEN)
  File "/home/slarse/Documents/github/cdate/repomate/repomate/github_api.py", line 496, in verify_settings
    if not REQUIRED_OAUTH_SCOPES.issubset(scopes):
TypeError: 'NoneType' object is not iterable
```

The problem is that, if `x-oauth-scopes` is not in the response object of the initial request to the github api, the `Github.oauth_scopes` property returns `None` (unexpected). What is also unexpected is that the user could be fetched from the host endpoint, which is _not_ the API endpoint... Strange.

**Comment by slarse** [comment]
It appears that all of the fields on the `NamedUser` object are None, so just adding a check for `fetched_user.login == user` should suffice in solving this issue. This may be a bug that should be reported to the PyGithub folks.
