### ISSUE TITLE
Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by oscekh** [slarse/repomate#134]
After running ``repomate -p junit4 clone -mn week-15 -rtd reference-tests/ -sf ../students
with config:

```
github_base_url = http://gits-15.sys.kth.se/api/v3/
user = oscarekh 
org_name = inda-18
students_file = /home/oscekh/Documents/INDA/18/students
token = xxxx
```
I get this trace:
```
[ERROR] unexpected exception raised before pre-initialization was complete. This shouldn't happen, please open an issue on GitHub and supply the stacktrace that follows below.
[ERROR] critical exception
Traceback (most recent call last):
  File "/home/oscekh/.local/lib/python3.7/site-packages/repomate/github_api.py", line 71, in _try_api_request
    yield
  File "/home/oscekh/.local/lib/python3.7/site-packages/repomate/github_api.py", line 114, in __init__
    self._org = self._github.get_organization(self._org_name)
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/MainClass.py", line 261, in get_organization
    "/orgs/" + login
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 324, in requestJson
    return self.__requestEncode(cnx, verb, url, parameters, headers, input, encode)
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 377, in __requestEncode
    status, responseHeaders, output = self.__requestRaw(cnx, verb, url, requestHeaders, encoded_input)
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 420, in __requestRaw
    return self.__requestRaw(original_cnx, verb, o.path, requestHeaders, input)
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 420, in __requestRaw
    return self.__requestRaw(original_cnx, verb, o.path, requestHeaders, input)
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 420, in __requestRaw
    return self.__requestRaw(original_cnx, verb, o.path, requestHeaders, input)
  [Previous line repeated 964 more times]
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 401, in __requestRaw
    response = cnx.getresponse()
  File "/home/oscekh/.local/lib/python3.7/site-packages/github/Requester.py", line 135, in getresponse
    r = verb(url, headers=self.headers, data=self.input, timeout=self.timeout, verify=self.verify, allow_redirects=False)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 320, in begin
    self.headers = self.msg = parse_headers(self.fp)
  File "/usr/lib/python3.7/http/client.py", line 214, in parse_headers
    return email.parser.Parser(_class=_class).parsestr(hstring)
  File "/usr/lib/python3.7/email/parser.py", line 68, in parsestr
    return self.parse(StringIO(text), headersonly=headersonly)
  File "/usr/lib/python3.7/email/parser.py", line 57, in parse
    feedparser.feed(data)
  File "/usr/lib/python3.7/email/feedparser.py", line 176, in feed
    self._call_parse()
  File "/usr/lib/python3.7/email/feedparser.py", line 180, in _call_parse
    self._parse()
  File "/usr/lib/python3.7/email/feedparser.py", line 224, in _parsegen
    for line in self._input:
  File "/usr/lib/python3.7/email/feedparser.py", line 129, in __next__
    line = self.readline()
  File "/usr/lib/python3.7/email/feedparser.py", line 89, in readline
    for ateof in reversed(self._eofstack):
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/oscekh/.local/lib/python3.7/site-packages/repomate/main.py", line 54, in main
    parsed_args, api = cli.parse_args(app_args)
  File "/home/oscekh/.local/lib/python3.7/site-packages/repomate/cli.py", line 116, in parse_args
    api = _connect_to_api(args.github_base_url, token, args.org_name)
  File "/home/oscekh/.local/lib/python3.7/site-packages/repomate/cli.py", line 672, in _connect_to_api
    api = github_api.GitHubAPI(github_base_url, token, org_name)
  File "/home/oscekh/.local/lib/python3.7/site-packages/repomate/github_api.py", line 114, in __init__
    self._org = self._github.get_organization(self._org_name)
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/oscekh/.local/lib/python3.7/site-packages/repomate/github_api.py", line 89, in _try_api_request
    "a {} occured unexpectedly: {}".format(type(e).__name__, str(e)))
repomate.exception.UnexpectedException: a RecursionError occured unexpectedly: maximum recursion depth exceeded while calling a Python object
```

**Comment by slarse** [comment]
The issue is caused by the url being `http` instead of `https` (it should be `https`). I'm guessing the recursion error has something to do with the HTTP library not correctly following the redirect to `https`. Will see if I can reproduce this and create some more informative error message in `verify-settings`.

**Comment by slarse** [comment]
@oscekh Hmm, I've been trying to reproduce this error but it doesn't work for me. I get an `InvalidURL` error, which is much easier to interpret. What version of Python are you running?

**Comment by oscekh** [comment]
Python 3.7.2

**Comment by slarse** [comment]
Me too. Weird. Well #149 will remove using http as an option, so that will resolve this particular issue as a side effect.

**Comment by slarse** [comment]
I think this should no longer be an issue that can occur.
