### ISSUE TITLE
pylint plugin crashes with an AttributeError

### ISSUE THREAD

**Issue by slarse** [slarse/repomate#84]
```
[CRITICAL] Traceback (most recent call last):
  File "/home/simon/.local/share/virtualenvs/repomate-ELEt9lT_/bin/repomate", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/simon/Documents/github/cdate/repomate/bin/repomate", line 6, in <module>
    main.main()
  File "/home/simon/Documents/github/cdate/repomate/repomate/main.py", line 39, in main
    cli.dispatch_command(parsed_args, api)
  File "/home/simon/Documents/github/cdate/repomate/repomate/cli.py", line 164, in dispatch_command
    command.clone_repos(args.master_repo_names, args.students, api)
  File "/home/simon/Documents/github/cdate/repomate/repomate/command.py", line 266, in clone_repos
    _execute_post_clone_hooks(repo_names)
  File "/home/simon/Documents/github/cdate/repomate/repomate/command.py", line 278, in _execute_post_clone_hooks
    LOGGER.info(_format_hook_results_output(results))
  File "/home/simon/Documents/github/cdate/repomate/repomate/command.py", line 398, in _format_hook_results_output
    for res in results
  File "/home/simon/Documents/github/cdate/repomate/repomate/command.py", line 398, in <listcomp>
    for res in results
  File "/home/simon/Documents/github/cdate/repomate/repomate/command.py", line 384, in _format_hook_result
    out += hook_result.hook + ": " + hook_result.status.name + style.RESET + os.linesep
AttributeError: 'str' object has no attribute 'name'
```

**Comment by slarse** [comment]
The `_pylint` function should return a HookResult

**Comment by slarse** [comment]
The first return in `act_on_cloned_repos` has a string in the `status` field of the `HookResult`, instead of a `Status` object.
